#!/bin/sh
#
# MIT License
#
# Copyright (c) 2018 Ingo Theiss <ingo.theiss@i-matrixx.de>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

### Global package definitions

# The package name
PACKAGE_NAME="Grafana"
# Package directory
PACKAGE_LOCATION="/var/packages/Grafana"
# Package scripts directory
PACKAGE_SCRIPTS_LOCATION="${PACKAGE_LOCATION}/scripts"
# Package target directory
PACKAGE_TARGET_LOCATION="${PACKAGE_LOCATION}/target"
# Grafana certificates
GRAFANA_SYNOLOGY_CERT_STORE="/usr/local/etc/certificate/Grafana/grafana-server"
# Grafana data directory
GRAFANA_DATA_DIR="${PACKAGE_TARGET_LOCATION}/grafana"
# Grafana plugin directory
GRAFANA_PLUGINS_DIR="${GRAFANA_DATA_DIR}/plugins"
# Grafana run directory (PID)
# The executed script name
SCRIPT_NAME="${0##*/}"

### Executable binary definitions

BIN_CHMOD="/bin/chmod"
BIN_CHOWN="/bin/chown"
BIN_CAT="/bin/cat"
BIN_CP="/bin/cp"
BIN_FIND="/bin/find"
BIN_LN="/bin/ln"
BIN_MKDIR="/bin/mkdir"
BIN_MV="/bin/mv"
BIN_RM="/bin/rm"
BIN_RMDIR="/bin/rmdir"
BIN_SERVICETOOL="/usr/syno/bin/servicetool"
BIN_SYNOPKGCTL="/usr/syno/sbin/synopkgctl"
BIN_SYNOSHARE="/usr/syno/sbin/synoshare"
BIN_SYNOUSER="/usr/syno/sbin/synouser"
